dev_directory : ./dev_data
eval_directory : ./eval_data
model_directory: ./model4
result_directory: ./result4
preprocessed_directory: ./preprocessed_data

max_fpr : 0.1

feature:
  n_mels: 128
  frames: 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

fit:
  compile:
    optimizer: adam
    loss: mean_squared_error
  epochs: 10
  batch_size: 1024
  shuffle: true
  validation_split: 0.1
  verbose: 1
  early_stopping_patience: 10
  reduce_lr_factor: 0.5
  reduce_lr_patience: 5
  min_lr: 1e-7

model:
  type: dense_ae
